Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -94,27 +94,27 @@ jobs:
       - name: Cargo test (full)
         run: cargo test --features=full --all-targets
 
-#   cargo-publish:
-#     if: github.event_name == 'push' && github.ref == 'refs/heads/master'
-#     env:
-#       CRATESIO_TOKEN: ${{ secrets.CRATESIO_TOKEN }}
-#     runs-on: ubuntu-latest
-#     steps:
-#       - uses: actions/checkout@v2
-#       - name: Update apt
-#         run: sudo apt update
-#       - name: Install alsa
-#         run: sudo apt install -y --no-install-recommends libasound2-dev pkg-config
-#       - name: Run cargo publish for crate
-#         continue-on-error: true
-#         run: |
-#           COG_TASK_TMP=$(mktemp /tmp/cog_taskXXX.txt) || echo "::error::mktemp error"
-#           echo "COG_TASK_TMP=$COG_TASK_TMP" >> $GITHUB_ENV
-#           cargo publish --token $CRATESIO_TOKEN 2> $COG_TASK_TMP
-#       - name: Check if crate is already published
-#         run: |
-#           empty=0
-#           COG_TASK_TMP="${{ env.COG_TASK_TMP }}"
-#           grep -q '[^[:space:]]' < $COG_TASK_TMP || empty=1
-#           [ $empty -eq 0 ] && cat $COG_TASK_TMP
-#           [ $empty -eq 1 ] || grep -q "is already uploaded" < $COG_TASK_TMP
+  cargo-publish:
+    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
+    env:
+      CRATESIO_TOKEN: ${{ secrets.CRATESIO_TOKEN }}
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - name: Update apt
+        run: sudo apt update
+      - name: Install alsa
+        run: sudo apt install -y --no-install-recommends libasound2-dev pkg-config
+      - name: Run cargo publish for crate
+        continue-on-error: true
+        run: |
+          COG_TASK_TMP=$(mktemp /tmp/cog_taskXXX.txt) || echo "::error::mktemp error"
+          echo "COG_TASK_TMP=$COG_TASK_TMP" >> $GITHUB_ENV
+          cargo publish --token $CRATESIO_TOKEN 2> $COG_TASK_TMP
+      - name: Check if crate is already published
+        run: |
+          empty=0
+          COG_TASK_TMP="${{ env.COG_TASK_TMP }}"
+          grep -q '[^[:space:]]' < $COG_TASK_TMP || empty=1
+          [ $empty -eq 0 ] && cat $COG_TASK_TMP
+          [ $empty -eq 1 ] || grep -q "is already uploaded" < $COG_TASK_TMP
